name: 'Test Cloudformation'

on:
  workflow_dispatch:
    inputs:
      resources:
        description: "Resources to test, empty will test all of resources available"
        default: ""
        required: true
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: jmimick/mdb-cfn-dev:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Test
        env:
          MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
          MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make test ${{ github.event.inputs.resources }}